### ISSUE TITLE
Unmarshalling into *map[string]string

### ISSUE THREAD

**Issue by rzhaovi** [viant/endly#55]
```
myfile.yaml
  start:
    action: docker:run
    image: name:v1
    target: 127.0.0.1
    ports: 
      - 7198:7198
```
```
[manager[Init]run datastore_Init: start: unable to create docker:run request failed to convert 7198:7198 to map[] du error]
datastore_Init: start: unable to create docker:run request failed to convert 7198:7198 to map[] due to Unable to convert type string into type *map[string]string
	7198:7198 at workflow.run at workflow.run
```
