### ISSUE TITLE
Custom stdin

### ISSUE THREAD

**Issue by NefixEstrada** [viant/endly#59]
Hello!

First of all thanks for this awesome tool, it's really useful!

There's a feature that I think would be really useful: being able to set a custom stdin for a command / execution.

**For example**: I want to test the password change feature of the app I'm testing. It's through the CLI and it asks for the old password and the new one twice

I'd be nice to have something like this:
```yaml
  test-change-password:
    action: exec:run
    target: $appTarget
    comment: This will change the password
    commands:
      - command: ./app passwd
        stdin:
          - oldpwd
          - newpwd
          - newpwd
```

It would be even better to be able to set custom waits between stdin entries!

Thanks!!
